### ISSUE TITLE
Invalid expression + no such node

### ISSUE THREAD

**Issue by plat00n** [sabakukyu/nagios-check_tomcat#1]
Hello,

I have one issue with the plugin (to catch the user & the pwd )

Error seems to happen here : 
```
function parse_xml()
{
        echo "cat //${1}" | xmllint --shell "${2}" | sed -r -n '/=/!d; s/^.*="([^"]+)"$/\1/p; q'
}
```
when i try to debug (with $1 & $2) : 
```
root@myserv:/usr/lib/nagios/plugins# echo "cat //user[contains(@roles,'\''manager-jmx'\'')]/@username" | xmllint --shell "/var/data/tomcat-8.0.30/server/instance_test/conf/tomcat-users.xml" | sed -r -n '/=/!d; s/^.*="([^"]+)"$/\1/p; q'
XPath error : Invalid expression
//user[contains(@roles,'\''manager-jmx'\'')]/@username
                          ^
xmlXPathEval: evaluation failed
//user[contains(@roles,'\''manager-jmx'\'')]/@username: no such node
```
Have you got one idea ?

Regards

**Comment by sabakukyu** [comment]
Could you give me the "tomcat-users.xml" file (passwords aren't needed)?  I would like to check how the "parse_xml" function is working on this file.

**Comment by plat00n** [comment]
Hello,

For sure :)

<?xml version='1.0' encoding='utf-8'?>

<tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">



        <role rolename="manager-script"/>
        <role rolename="tomcat"/>
        <user username="tomcat" password="pwd" roles="tomcat,admin,manager-gui,manager-script"/>
        <user username="nagios" password="nagios" roles="tomcat,manager-jmx"/>

</tomcat-users>

**Comment by sabakukyu** [comment]
I have been performing some tests and the "parse_xml" function should work with this configuration. If you want to test it manually, you should run the following command:

echo "cat //user[contains(@roles,'manager-jmx')]/@username" | xmllint --shell "/var/data/tomcat-8.0.30/server/instance_test/conf/tomcat-users.xml" | sed -r -n '/=/!d; s/^.*="([^"]+)"$/\1/p; q'

Notice that there's only one "'". What's the result of this execution?

**Comment by plat00n** [comment]
No result 

```
root@myserv:~# echo "cat //user[contains(@roles,'manager-jmx')]/@username" | xmllint --shell "/var/data/tomcat-8.0.30/server/instance_test/conf/tomcat-users.xml" | sed -r -n '/=/!d; s/^.*="([^"]+)"$/\1/p; q'
root@myserv:~#
```
same thing with the adress =>
```
root@myserv:~# echo "cat //Connector[@protocol='HTTP/1.1']/@address" | xmllint --shell "/var/data/tomcat-8.0.30/server/instance_test/conf/server.xml" | sed -r -n '/=/!d; s/^.*="([^"]+)"$/\1/p; q'
root@myserv:~#
```

```
root@myserv:~# xmllint --debug "/var/data/tomcat-8.0.30/server/instance_test/conf/tomcat-users.xml"
DOCUMENT
version=1.0
encoding=utf-8
URL=/var/data/softwares/tomcat-8.0.30/server...
standalone=true
  COMMENT
    content=   Licensed to the Apache Software Found...
  ELEMENT tomcat-users
    default namespace href=http://tomcat.apache.org/xml
    namespace xsi href=http://www.w3.org/2001/XMLSchema-instanc...
    ATTRIBUTE schemaLocation
      TEXT
        content=http://tomcat.apache.org/xml tomcat-user...
    ATTRIBUTE version
      TEXT compact
        content=1.0
    TEXT compact
      content=
    COMMENT
      content=   NOTE:  By default, no user is include...
    TEXT compact
      content=
    COMMENT
      content=   NOTE:  The sample user and role entri...
    TEXT compact
      content=
    COMMENT
      content=   <role rolename="tomcat"/>   <role rol...
    TEXT compact
      content=
    ELEMENT role
      ATTRIBUTE rolename
        TEXT compact
          content=manager-script
    TEXT compact
      content=
    ELEMENT role
      ATTRIBUTE rolename
        TEXT compact
          content=tomcat
    TEXT compact
      content=
    ELEMENT user
      ATTRIBUTE username
        TEXT compact
          content=tomcat
      ATTRIBUTE password
        TEXT compact
          content=pwd
      ATTRIBUTE roles
        TEXT
          content=tomcat,admin,manager-gui,manager-script
    TEXT compact
      content=
    ELEMENT user
      ATTRIBUTE username
        TEXT compact
          content=nagios
      ATTRIBUTE password
        TEXT compact
          content=nagios
      ATTRIBUTE roles
        TEXT
          content=tomcat,manager-jmx
    TEXT compact
      content=
```

**Comment by sabakukyu** [comment]
Seems that the file is empty or commented..., no sense. There are no comments, right? (I know, it's a stupid question).

First of all, can you run the same command without "sed"? (only "cat" + "xmllint"). Second, I would need the original file (tomcat-users.xml or server.xml) to do more tests.

**Comment by plat00n** [comment]
rights + owner  = -rwxr-xr-x 1 tomcat tomcat
[tomcat-users.xml.txt](https://github.com/sabakukyu/nagios-check_tomcat/files/772001/tomcat-users.xml.txt)

```
root@myserv:/usr/lib/nagios/plugins# echo "cat //user[contains(@roles,'manager-jmx')]/@username" | xmllint --shell "/var/data/tomcat-8.0.30/server/instance_test/conf/tomcat-users.xml"
/ > cat //user[contains(@roles,'manager-jmx')]/@username
/ > root@myserv:/usr/lib/nagios/plugins#
```

**Comment by sabakukyu** [comment]
Gotcha! The main problem is the presence of XML Namespaces in file. If you try to run the same query on a xml without namespaces the result is correct (testing file: [tomcat-users.xml_noxmlns.txt](https://github.com/sabakukyu/nagios-check_tomcat/files/773759/tomcat-users.xml_noxmlns.txt)):

[me@myserver ~]$ echo "cat //user[contains(@roles, 'manager-jmx')]/@username" | xmllint --shell "./tomcat-users.xml_noxmlns"
/ >  -------
 username="nagios"
/ >

The right query on a xml with namespaces would be the following:

[me@myserver ~]$ echo "cat //*[local-name()='user'][contains(@roles, 'manager-jmx')]/@username" | xmllint --shell "./tomcat-users.xml"
/ >  -------
 username="nagios"
/ >

The check_tomcat plugin is not designed to work with XML Namespaces. You must change manually the xml files or the plugin (all the queries calling the "parse_xml" function). I'm sorry!
